# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UafPPBmPKKsiB5xQHGuPlQVeO2h7RYV7
"""

# Importar librerías
import pandas as pd
import numpy as np
import pickle

# ==============================================================================
# FASE 1: COMPRENSIÓN DEL NEGOCIO (Parámetros de Velocidad)
# ==============================================================================
print("--- FASE 1: DEFINICIÓN DE OBJETIVOS (VELOCIDAD ULTRA-RÁPIDA) ---")

# Parámetros ÁGILES para Máxima Velocidad
MAX_LEN = 10
RNN_UNITS = 16   # Reducción de 32 a 16
EMBEDDING_DIM = 32 # Reducción de 64 a 32
TEST_SIZE = 0.2
EPOCHS = 5       # Entrenamiento muy corto
BATCH_SIZE = 128 # Aumento para menos pasos por época

print(f"RNN Units: {RNN_UNITS}, Embedding Dim: {EMBEDDING_DIM}, Epochs: {EPOCHS}")
print("-" * 60)

# ==============================================================================
# FASE 2: DATOS (Carga y Control de Calidad)
# ==============================================================================
print("--- FASE 2: CARGA Y CONTROL DE CALIDAD DE LOS DATOS ---")

# Carga de Datos
try:
    df = pd.read_csv('data.csv')
except FileNotFoundError:
    print("❌ Error: Asegúrate de que 'data.csv' esté cargado en tu entorno Colab.")
    raise

# Control de Calidad
df.dropna(inplace=True)
print(f"Número de pares de frases después de la limpieza: {len(df)}")

# Preparación de listas de frases y etiqueta de fin
input_texts = df['spanish'].astype(str).tolist()
target_texts = df['english'].astype(str).tolist()
target_texts_output = [text + ' endofseq' for text in target_texts]

print("Etiquetas 'endofseq' añadidas.")
print("-" * 60)

# 💾 GUARDAR DATOS Y PARÁMETROS
with open('processed_data.pkl', 'wb') as f:
    pickle.dump({
        'input_texts': input_texts,
        'target_texts_output': target_texts_output,
        'MAX_LEN': MAX_LEN, 'TEST_SIZE': TEST_SIZE,
        'RNN_UNITS': RNN_UNITS, 'EMBEDDING_DIM': EMBEDDING_DIM,
        'EPOCHS': EPOCHS, 'BATCH_SIZE': BATCH_SIZE
    }, f)
print("Datos y parámetros guardados en 'processed_data.pkl'.")

# Importar librerías
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
import pickle

# Cargar datos y parámetros
try:
    with open('processed_data.pkl', 'rb') as f:
        data = pickle.load(f)
    input_texts = data['input_texts']
    target_texts_output = data['target_texts_output']
    MAX_LEN = data['MAX_LEN']
    TEST_SIZE = data['TEST_SIZE']
except FileNotFoundError:
    print("❌ Error: Ejecuta el Bloque 1 primero.")
    raise

# ==============================================================================
# FASE 3: PREPARACIÓN DE LOS DATOS (Conversión y Alineación)
# ==============================================================================
print("--- FASE 3: PREPARACIÓN DE LOS DATOS ---")

# Aspecto: Conversión Numérica (Tokenizadores)
spa_tokenizer = Tokenizer()
spa_tokenizer.fit_on_texts(input_texts)
input_sequences = spa_tokenizer.texts_to_sequences(input_texts)
spa_vocab_size = len(spa_tokenizer.word_index) + 1

eng_tokenizer = Tokenizer(filters='')
eng_tokenizer.fit_on_texts(target_texts_output)
target_sequences = eng_tokenizer.texts_to_sequences(target_texts_output)
eng_vocab_size = len(eng_tokenizer.word_index) + 1

# Aspecto: Secuenciación y Alineación (Padding)
encoder_input_data = pad_sequences(input_sequences, maxlen=MAX_LEN, padding='post')
decoder_target_data = pad_sequences(target_sequences, maxlen=MAX_LEN, padding='post')
decoder_target_data = np.expand_dims(decoder_target_data, -1)

# Aspecto: División Final (Train/Test Split)
X_train, X_test, y_train, y_test = train_test_split(
    encoder_input_data, decoder_target_data, test_size=TEST_SIZE, random_state=42
)
print(f"Datos de Entrenamiento (X_train): {X_train.shape}, Test (X_test): {X_test.shape}")
print("-" * 60)

# 💾 GUARDAR DATOS PROCESADOS PARA EL SIGUIENTE BLOQUE
with open('processed_data_f3.pkl', 'wb') as f:
    pickle.dump({
        'X_train': X_train, 'X_test': X_test, 'y_train': y_train, 'y_test': y_test,
        'spa_vocab_size': spa_vocab_size, 'eng_vocab_size': eng_vocab_size,
        'spa_tokenizer': spa_tokenizer, 'eng_tokenizer': eng_tokenizer,
        'MAX_LEN': MAX_LEN, 'RNN_UNITS': data['RNN_UNITS'],
        'EMBEDDING_DIM': data['EMBEDDING_DIM'], 'EPOCHS': data['EPOCHS'],
        'BATCH_SIZE': data['BATCH_SIZE']
    }, f)
print("Datos tokenizados y divididos guardados en 'processed_data_f3.pkl'.")

# Importar librerías
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
import pickle

# Cargar datos y parámetros
try:
    with open('processed_data_f3.pkl', 'rb') as f:
        data_f3 = pickle.load(f)

    X_train = data_f3['X_train']
    y_train = data_f3['y_train']
    X_test = data_f3['X_test']
    y_test = data_f3['y_test']

    spa_vocab_size = data_f3['spa_vocab_size']
    eng_vocab_size = data_f3['eng_vocab_size']
    MAX_LEN = data_f3['MAX_LEN']
    RNN_UNITS = data_f3['RNN_UNITS']
    EMBEDDING_DIM = data_f3['EMBEDDING_DIM']
    EPOCHS = data_f3['EPOCHS']
    BATCH_SIZE = data_f3['BATCH_SIZE']

except FileNotFoundError:
    print("❌ Error: Ejecuta el Bloque 2 primero.")
    raise

# ==============================================================================
# FASE 4: MODELADO Y ENTRENAMIENTO
# ==============================================================================
print("--- FASE 4: MODELADO Y ENTRENAMIENTO RÁPIDO ---")

# Aspecto: Construcción del Modelo
model = Sequential([
    Embedding(spa_vocab_size, EMBEDDING_DIM, input_length=MAX_LEN, mask_zero=True),
    SimpleRNN(RNN_UNITS, return_sequences=True),
    Dense(eng_vocab_size, activation='softmax')
])

# Aspecto: Compilación del Modelo
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

print("🚀 Arquitectura del Modelo:")
model.summary()
print("-" * 30)


# Aspecto: Entrenamiento del Modelo (Ejecución)
print(f"Iniciando **ENTRENAMIENTO** con {EPOCHS} épocas y BATCH_SIZE={BATCH_SIZE}...")
history = model.fit(
    X_train,
    y_train,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    validation_data=(X_test, y_test),
    verbose=1
)

print("-" * 60)
print("✅ Entrenamiento completado. El historial se pasa a la Fase 5.")

# 💾 GUARDAR MODELO Y EL HISTORIAL
model.save('model_trained_fast.keras')
with open('training_history.pkl', 'wb') as f:
    pickle.dump(history.history, f)
print("Modelo entrenado y el historial de entrenamiento guardados.")

# Importar librerías
import pickle
import matplotlib.pyplot as plt

# Cargar el historial de entrenamiento
try:
    with open('training_history.pkl', 'rb') as f:
        history_data = pickle.load(f)

except FileNotFoundError:
    print("❌ Error: Ejecuta el Bloque 3 primero.")
    raise

# ==============================================================================
# FASE 5: MÉTRICAS (Evaluación y Visualización)
# ==============================================================================
print("--- FASE 5: MÉTRICAS ---")

# Aspecto: Resumen de Resultados
final_val_loss = history_data['val_loss'][-1]
final_val_accuracy = history_data['val_accuracy'][-1]

print("📊 RESUMEN DE MÉTRICAS (Última Época):")
print(f"Pérdida de Validación (Loss): {final_val_loss:.4f}")
print(f"Precisión de Validación (Accuracy): {final_val_accuracy:.4f} ({final_val_accuracy * 100:.2f}%)")
print("Nota: Los valores son bajos debido a la estrategia de entrenamiento ultra-rápido.")


# Aspecto: Visualización de Matrices (Gráficos)
plt.figure(figsize=(12, 5))

# Gráfico de Pérdida (Loss)
plt.subplot(1, 2, 1)
plt.plot(history_data['loss'], label='Pérdida (Train)')
plt.plot(history_data['val_loss'], label='Pérdida (Validation)')
plt.title('Pérdida del Modelo por Época')
plt.ylabel('Pérdida (Loss)')
plt.xlabel('Época')
plt.legend()

# Gráfico de Precisión (Accuracy)
plt.subplot(1, 2, 2)
plt.plot(history_data['accuracy'], label='Precisión (Train)')
plt.plot(history_data['val_accuracy'], label='Precisión (Validation)')
plt.title('Precisión del Modelo por Época')
plt.ylabel('Precisión')
plt.xlabel('Época')
plt.legend()

plt.show()

print("-" * 60)
print("✅ Análisis de métricas completado.")

# Importar librerías
import pickle
from tensorflow.keras.models import load_model

# Cargar objetos necesarios
try:
    with open('processed_data_f3.pkl', 'rb') as f:
        data_f3 = pickle.load(f)
    spa_tokenizer = data_f3['spa_tokenizer']
    eng_tokenizer = data_f3['eng_tokenizer']

    # Verificar la existencia del modelo entrenado
    model = load_model('model_trained_fast.keras')

except FileNotFoundError:
    print("❌ Error: Asegúrate de ejecutar el Bloque 3 primero.")
    raise

# ==============================================================================
# FASE 6: DESPLIEGUE (SERIALIZACIÓN DE ACTIVOS)
# ==============================================================================
print("--- FASE 6: DESPLIEGUE (SERIALIZACIÓN DE ACTIVOS) ---")

# Aspecto: Serialización del Modelo
print("💾 Modelo entrenado 'model_trained_fast.keras' listo para el despliegue.")

# Aspecto: Serialización de los Tokenizadores
# Guardar el tokenizador de español
with open('spa_tokenizer_fast.pickle', 'wb') as handle:
    pickle.dump(spa_tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)
print("💾 Tokenizador de Español (spa_tokenizer_fast.pickle) guardado.")

# Guardar el tokenizador de inglés
with open('eng_tokenizer_fast.pickle', 'wb') as handle:
    pickle.dump(eng_tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)
print("💾 Tokenizador de Inglés (eng_tokenizer_fast.pickle) guardado.")

print("Todos los activos necesarios han sido serializados.")
print("-" * 60)